
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PenParadise.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ProductType
{

    public ProductType()
    {

        this.Categories = new HashSet<Category>();

    }


    public string ProducTypeID { get; set; }

    public string ProductTypeName { get; set; }



    public virtual ICollection<Category> Categories { get; set; }

}

}
